# Generated by Django 5.0.9 on 2024-10-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0015_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='actual_completed_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='target_date',
        ),
    ]
