# Generated by Django 5.0.9 on 2024-10-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0019_alter_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='percent_constituting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='clg_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_app.college'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_app.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_app.user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
    ]
