# Generated by Django 5.0.9 on 2024-10-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0021_subject_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='total_hours',
        ),
    ]
