# Generated by Django 5.0.9 on 2024-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0022_remove_subject_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='totalhours',
            field=models.IntegerField(default=0),
        ),
    ]
