# Generated by Django 5.0.9 on 2024-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0023_lessonplan_totalhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='completedhours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='completedpercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='pendinghours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='pendingpercent',
            field=models.IntegerField(default=0),
        ),
    ]
