# Generated by Django 5.0.9 on 2024-10-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0028_rename_expectedpercenthourstocomplete_lessonplan_expectedhourstocomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Duration',
            new_name='totalhours',
        ),
    ]
