# Generated by Django 3.2.25 on 2024-09-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0011_alter_approval_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IA', 'Inactive')], default='IA', max_length=10),
        ),
    ]
