# Generated by Django 3.2.25 on 2024-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0012_alter_lessonplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
