# Generated by Django 3.2.25 on 2024-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0013_alter_user_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sec',
            field=models.CharField(max_length=10),
        ),
    ]
