# Generated by Django 5.0.9 on 2024-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0016_remove_topic_actual_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CO', 'Completed'), ('PE', 'Pending for Approval'), ('RE', 'Rejected'), ('NC', 'Not Created')], default='NC', max_length=10),
        ),
    ]
