# Generated by Django 5.0.9 on 2024-10-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0017_alter_lessonplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending for Approval', 'Pending for Approval'), ('Rejected', 'Rejected'), ('Not Created', 'Not Created')], default='Not Created', max_length=40),
        ),
    ]
