# Generated by Django 5.0.9 on 2024-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0018_alter_lessonplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Not Started', max_length=50),
        ),
    ]
