# Generated by Django 5.0.9 on 2024-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0025_lessonplan_expectedpercenthourstocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hoursperweek',
            field=models.IntegerField(default=1),
        ),
    ]
