# Generated by Django 5.0.9 on 2024-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0026_subject_hoursperweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='subject',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
