# Generated by Django 5.0.9 on 2024-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0029_rename_duration_subject_totalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending For Approval', 'Pending For Approval'), ('Rejected', 'Rejected'), ('Not Created', 'Not Created')], default='Not Created', max_length=40),
        ),
    ]
