# Generated by Django 5.0.9 on 2024-10-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0030_alter_lessonplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='name',
        ),
    ]
